import streamlit as st

st.title("Информация о наборе данных:")
st.header("Тематика датасета: Операции банковской карты")
st.header("Описание признаков:")
st.write("- distance_from_home: расстояние от дома владельца карты")
st.write("- distance_from_last_transaction: расстояние от последней транзакции с карты")
st.write("- ratio_to_median_purchase_price: различие от средней цены покупки")
st.write("- repeat_retailer: совершались ли транзакции у этого ритейлера раньше")
st.write("- used_chip: использовался ли чип")
st.write("- used_pin_number: использовался ли пинкод")
st.write("- online_order: была ли покупка онлайн")
st.header(" Предобработка данных:")
st.write("В датасете были пропущенные значения. Они были удалены")
st.write("Были удалены дубликаты")
st.write("Устранён дисбаланс классов")